# Generated by Django 5.0.4 on 2024-04-24 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('det_valor', models.TextField()),
                ('det_fk_variable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='variable.variable')),
            ],
        ),
    ]
