# Generated by Django 5.0.4 on 2024-04-24 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle', '0001_initial'),
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='det_fk_ficha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ficha.ficha'),
        ),
    ]
