# Generated by Django 5.0.4 on 2024-04-24 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sit_nombre', models.CharField(max_length=100)),
                ('sit_fk_areas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Area.area')),
            ],
        ),
    ]
