# Generated by Django 5.0.4 on 2024-04-24 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0001_initial'),
        ('TipoSitio', '0002_remove_tipositio_idtipo_sitio_tipositio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio',
            name='sit_fk_tipo_sitio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TipoSitio.tipositio'),
        ),
    ]
