# Generated by Django 5.0.4 on 2024-04-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=255)),
                ('regional', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('subdirector', models.CharField(max_length=100)),
            ],
        ),
    ]
