# Generated by Django 5.0.4 on 2024-04-24 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Centro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centro',
            old_name='descripcion',
            new_name='cen_descripcion',
        ),
        migrations.RenameField(
            model_name='centro',
            old_name='municipio',
            new_name='cen_municipio',
        ),
        migrations.RenameField(
            model_name='centro',
            old_name='nombre',
            new_name='cen_nombre',
        ),
        migrations.RenameField(
            model_name='centro',
            old_name='regional',
            new_name='cen_regional',
        ),
        migrations.RenameField(
            model_name='centro',
            old_name='subdirector',
            new_name='cen_subdirector',
        ),
    ]
