# Generated by Django 5.0.4 on 2024-04-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_equipo',
            fields=[
                ('idTipo_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('ti_fi_nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
