# Generated by Django 5.0.4 on 2024-04-24 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipoEquipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('idVariable', models.AutoField(primary_key=True, serialize=False)),
                ('var_nombre', models.CharField(max_length=100)),
                ('var_descripcion', models.TextField()),
                ('var_fk_tipo_ficha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipoEquipo.tipo_equipo')),
            ],
        ),
    ]
