# Generated by Django 5.0.2 on 2024-04-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_mantenimiento_models',
            name='tipo_prueva',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
