# Generated by Django 5.0.4 on 2024-04-24 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sede', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_nombre', models.CharField(max_length=255)),
                ('area_fk_sedes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sede.sede')),
            ],
        ),
    ]
