# Generated by Django 5.0.4 on 2024-04-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idActividades', models.IntegerField()),
                ('acti_nombre', models.CharField(max_length=255)),
                ('acti_descripcion', models.TextField()),
                ('acti_fecha_realizacion', models.DateTimeField(auto_now_add=True)),
                ('acti_estado', models.CharField(max_length=255)),
                ('fk_mantenimiento', models.IntegerField()),
            ],
        ),
    ]
