# Generated by Django 5.0.4 on 2024-04-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0002_alter_actividades_acti_fecha_realizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='acti_fecha_realizacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
