# Generated by Django 5.0.4 on 2024-04-24 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipoEquipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('idFichas', models.AutoField(primary_key=True, serialize=False)),
                ('fi_fecha', models.DateField()),
                ('fi_placa_sena', models.CharField(max_length=100)),
                ('fi_serial', models.CharField(max_length=100)),
                ('fi_fecha_adquisicion', models.DateField()),
                ('fi_fecha_inicioGarantia', models.DateField()),
                ('fi_fecha_finGarantia', models.DateField()),
                ('fi_descripcionGarantia', models.TextField()),
                ('fi_imagen', models.CharField(max_length=100)),
                ('fi_estado', models.CharField(choices=[('Operacion', 'Operacion'), ('fuera_de_servicio', 'fuera_de_servicio'), ('En_reparacion', 'En_reparacion')], max_length=20)),
                ('fi_fk_tipoFicha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipoEquipo.tipo_equipo')),
            ],
        ),
    ]
