# Generated by Django 5.0.4 on 2024-04-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TipoSitio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipositio',
            name='idTipo_sitio',
        ),
        migrations.AddField(
            model_name='tipositio',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
