# Generated by Django 5.0.2 on 2024-04-24 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mantenimiento_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mant_codigo_mantenimiento', models.CharField(max_length=50)),
                ('mant_fecha_realizacion', models.DateTimeField(auto_now_add=True)),
                ('mant_fecha_proxima', models.DateTimeField(auto_now_add=True)),
                ('mant_descripcion', models.CharField(max_length=100)),
                ('mant_fk_mantenimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo_mantenimiento.tipo_mantenimiento_models')),
            ],
        ),
    ]
