# Generated by Django 5.0.2 on 2024-04-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento_models',
            name='mant_fecha_proxima',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento_models',
            name='mant_fecha_realizacion',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
